
export class CreateLeaderDto {
    _id?: string;
    nombres: string;
    apellidos: string;
    tipoDocumento: string;
    numeroDocumento: string;
    celular: string;
    telefono?: string;
    email?: string;
    company?: string;
    nickname?: string;
    lat?: string;
    lng?: string;
    fechaNacimiento: string;
    sexo: string;
    direccion: string;
    comuna: string;
    barrio: string;
    vereda?: string;
    corregimiento?: string;
    departamento: string;
    ciudad: string;
    tipoLider: string;
    urlFoto: string;
    originalNameFoto?: string;
    uuidFoto?: string;
    zonaInfluencia: string;
    numeroVotantes: string;
    fechaCreacion?: string;
    fechaModificacion?: string;
    horaModificacion?: string;
    horaCreacion?: string;
    idUserModificacion?: string;
    isUserModule?: boolean;
    idUser: string;
    campaign?: any;
    redirectUri?: string;
}
